name: Pull Request Checks

on: pull_request

jobs:
  tests:
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies [node $${{ matrix.node-version }}]
        run: npm ci
      
      - name: Run tests [node $${{ matrix.node-version }}]
        run: npm test

      - name: coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          output: report-markdown
          coverage-file: ./coverage/coverage-final.json     
      
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
