name: Push coverage report

on: 
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test

      - name: Setup sonar
        uses: warchant/setup-sonar-scanner@v3
      - run: sonar-scanner
          -Dsonar.projectKey=mock-github
          -Dsonar.projectName="mock-github"
          -Dsonar.sources=$GITHUB_WORKSPACE
          -Dsonar.host.url=${{ secrets.SONAR_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.tests=test
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.exclusions="test/**,jest.config.ts,*json, **/*.constants.ts, **/*.types.ts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
